name: On merge

on:
  push:
    branches:
      - master

jobs:
  release-publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GH_SSH_PRIVATE_KEY_JAHIACI }}

      - name: Install dependencies
        shell: bash
        run: yarn install --frozen-lockfile

      - name: Build
        shell: bash
        run: yarn build

      - name: Release and publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
        shell: bash
        run: |
          git fetch --tags
          yarn release

      - name: Merge changes back into develop branch
        shell: bash
        run: |
          git checkout develop
          git merge master --ff-only
          git push -u origin develop
