name: On merge

on:
  push:
    branches:
      - master

jobs:
  release-publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    steps:
      # Providing the SSH PRIVATE of a user part of an admin group
      # is necessary to bypass PR checks
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY_JAHIACI }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
      # Setting up the SSH agent to be able to commit back to the repository
      # https://github.com/webfactory/ssh-agent
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.GH_SSH_PRIVATE_KEY_JAHIACI }}

      - name: Install dependencies
        shell: bash
        run: yarn install --frozen-lockfile

      - name: Build
        shell: bash
        run: yarn build

      - name: Release and publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
        shell: bash
        run: |
          git fetch --tags
          yarn release

      - name: Merge changes back into develop branch
        shell: bash
        run: |
          git checkout develop
          git merge master --ff-only
          git push -u origin develop
