name: Release

on:
  push:
    branches:
      - main
  release:
    types:
      - published
      - released
  workflow_dispatch: null

jobs:
  publish-release:
    runs-on: ubuntu-slim
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - name: Build and publish
        run: >
          corepack enable && yarn install

          yarn workspaces foreach -vv --all --topological-dev run build

          yarn workspaces foreach -vv --all --topological --no-private npm publish --access public
          --tolerate-republish --provenance
      - run: npx chachalog@^0.5.0 publish-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-storybook:
    # only run on non-prerelease GitHub releases
    if: ${{ github.event_name == 'release' && !github.event.release.prerelease }}
    runs-on: ubuntu-latest
    permissions:
      pages: write      # required to deploy to GitHub Pages
      id-token: write   # required for OIDC authentication
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # displays deployed URL in Actions tab
    steps:
      - name: Checkout release tag
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Build the storybook
        run: |
          corepack enable && yarn install --immutable
          yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # packages storybook-static for deployment
        with:
          path: storybook-static

      - name: Deploy to GitHub Pages
        id: deployment # id needed to expose page_url output
        uses: actions/deploy-pages@v4
